### PR TITLE
Replace user made packages with superdesk forked versions

### PR DESCRIPTION
**Pull request by thecalcc**

### CODE REVIEW

**Comment by tomaskikutis** [comment]
it'd be good to fix the build/tests even if it wasn't your PR that broke it

**Comment by thecalcc** [comment]
I can't fix the backend lint `Lint / flake8`

**Comment by tomaskikutis** [comment]
@petrjasek could you fix the `Lint / flake8 ` thing?

**Comment by petrjasek** [comment]
fixed in https://github.com/superdesk/superdesk-analytics/pull/150

**Review by devketanpro — APPROVED** [review]

**Pull request merged**
